import { z } from "zod";

export const listProductsQuerySchema = z.object({
  unitId: z.string().cuid("Unit ID tidak valid")
});

export const createProductSchema = z.object({
  unitId: z.string().cuid("Unit ID tidak valid"),
  sku: z.string().min(1, "SKU wajib diisi"),
  name: z.string().min(1, "Nama produk wajib diisi"),
  category: z.string().min(1).optional(),
  uom: z.string().min(1).optional(),
  sellPrice: z.coerce.number().nonnegative("Harga jual tidak boleh negatif"),
  costPrice: z.coerce.number().nonnegative("Harga beli tidak boleh negatif")
});

// "OUT" is intentionally not a valid input here — it's system-generated by
// POS sale posting (a later task), not manually enterable through this route.
export const recordStockMovementSchema = z.object({
  type: z.enum(["IN", "ADJUSTMENT"], {
    errorMap: () => ({ message: "Tipe pergerakan stok harus IN atau ADJUSTMENT" })
  }),
  quantity: z.coerce.number().int().positive("Jumlah harus lebih dari 0"),
  reason: z.string().min(1, "Alasan wajib diisi")
});

export const listStockMovementsQuerySchema = z.object({
  unitId: z.string().cuid("Unit ID tidak valid")
});

export type ListProductsQueryInput = z.infer<typeof listProductsQuerySchema>;
export type CreateProductInput = z.infer<typeof createProductSchema>;
export type RecordStockMovementInput = z.infer<typeof recordStockMovementSchema>;
export type ListStockMovementsQueryInput = z.infer<typeof listStockMovementsQuerySchema>;
