import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { StockMovementType } from "@siskop/types";
import { getProducts, recordStockMovement } from "@/api/konsumen";
import { ApiRequestError } from "@/api/client";
import { useToast } from "@/hooks/use-toast";
import { FormError } from "@/components/shared/FormError";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

// Manual stock-in/adjustment entry — "OUT" is deliberately not offered here,
// it's system-generated by POS sale posting (product.schema.ts's
// recordStockMovementSchema also rejects it server-side).
const MOVEMENT_TYPES: StockMovementType[] = ["IN", "ADJUSTMENT"];
const MOVEMENT_TYPE_LABEL: Record<StockMovementType, string> = {
  IN: "Stok Masuk — tambah ke stok saat ini",
  ADJUSTMENT: "Penyesuaian — atur ulang jumlah stok"
};

// Same shape/validation as product.service.ts#recordStockMovement:
// quantity must be a positive integer, checked client-side too (not just
// relying on the server 400) so the error shows inline before a round trip.
const schema = z.object({
  productId: z.string().min(1, "Pilih produk"),
  type: z.enum(["IN", "ADJUSTMENT"]),
  quantity: z.coerce.number().int().positive("Jumlah harus lebih dari 0"),
  reason: z.string().min(1, "Alasan wajib diisi")
});
type FormValues = z.infer<typeof schema>;

const DEFAULT_VALUES: FormValues = { productId: "", type: "IN", quantity: 0, reason: "" };

export function StockMovementForm({ unitId }: { unitId: string }) {
  const { toast } = useToast();
  const qc = useQueryClient();

  // Same ["konsumen","products",unitId] cache key ProductsPage/CreateProductDialog
  // use — picking a product to record a movement for shares that cache
  // instead of a redundant fetch.
  const { data: products } = useQuery({
    queryKey: ["konsumen", "products", unitId],
    queryFn: () => getProducts(unitId)
  });

  const {
    register,
    handleSubmit,
    reset,
    setValue,
    watch,
    formState: { errors }
  } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: DEFAULT_VALUES });
  const values = watch();

  const mutation = useMutation({
    mutationFn: (v: FormValues) =>
      recordStockMovement(v.productId, { type: v.type, quantity: v.quantity, reason: v.reason }),
    onSuccess: () => {
      toast({ title: "Pergerakan stok dicatat" });
      void qc.invalidateQueries({ queryKey: ["konsumen", "stock-movements", unitId] });
      void qc.invalidateQueries({ queryKey: ["konsumen", "products", unitId] });
      reset(DEFAULT_VALUES);
    },
    onError: (err) => {
      toast({
        title: "Gagal mencatat pergerakan stok",
        description: err instanceof ApiRequestError ? err.message : "Terjadi kesalahan",
        variant: "destructive"
      });
    }
  });

  const onSubmit = (v: FormValues) => mutation.mutate(v);

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Catat Pergerakan Stok</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          {mutation.isError && (
            <FormError error={mutation.error instanceof ApiRequestError ? mutation.error.message : "Terjadi kesalahan"} />
          )}

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label>Produk *</Label>
              <Select value={values.productId} onValueChange={(v) => setValue("productId", v)}>
                <SelectTrigger>
                  <SelectValue placeholder="Pilih produk" />
                </SelectTrigger>
                <SelectContent>
                  {(products ?? []).map((p) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.sku} — {p.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.productId && <p className="text-xs text-destructive">{errors.productId.message}</p>}
            </div>

            <div className="space-y-1.5">
              <Label>Jenis *</Label>
              <Select value={values.type} onValueChange={(v: FormValues["type"]) => setValue("type", v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {MOVEMENT_TYPES.map((t) => (
                    <SelectItem key={t} value={t}>
                      {MOVEMENT_TYPE_LABEL[t]}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label>Jumlah *</Label>
              <Input type="number" min="1" step="1" {...register("quantity")} />
              {errors.quantity && <p className="text-xs text-destructive">{errors.quantity.message}</p>}
            </div>
            <div className="space-y-1.5">
              <Label>Alasan *</Label>
              <Input placeholder="Pembelian dari supplier" {...register("reason")} />
              {errors.reason && <p className="text-xs text-destructive">{errors.reason.message}</p>}
            </div>
          </div>

          <div className="flex justify-end">
            <Button type="submit" disabled={mutation.isPending}>
              {mutation.isPending ? "Menyimpan..." : "Catat Pergerakan"}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
