// KSU Konsumen (Toko/POS) — Phase 2 Task 2: Product CRUD + stock-movement
// tracking, scoped to a KONSUMEN-type CooperativeUnit. Field names here match
// the Phase 4 frontend plan (docs/ksu-konsumen-frontend.md) exactly, which is
// why they diverge from the raw Prisma column names (`price`/`cost`/
// `stockQty` become `sellPrice`/`costPrice`/`stockLevel` over the wire).

export type StockMovementType = "IN" | "ADJUSTMENT";

/** A Konsumen/Toko product (Prisma `Product`), serialized for the API. */
export interface Product {
  id: string;
  sku: string;
  name: string;
  category: string | null;
  uom: string;
  /** Product.price, Decimal(15,2) serialized as a string over the wire. */
  sellPrice: string;
  /** Product.cost, Decimal(15,2) serialized as a string over the wire. */
  costPrice: string;
  /** Product.stockQty (a plain int), exposed as a string per this contract. */
  stockLevel: string;
  isActive: boolean;
}

export interface CreateProductRequest {
  /** unitId must resolve to a KONSUMEN-type CooperativeUnit owned by the caller's tenant. */
  unitId: string;
  sku: string;
  name: string;
  category?: string;
  uom?: string;
  sellPrice: string | number;
  costPrice: string | number;
}

/**
 * `"OUT"` is deliberately not accepted here — it is system-generated by POS
 * sale posting (a later task), never manually entered by a caller of this
 * endpoint.
 */
export interface RecordStockMovementRequest {
  type: StockMovementType;
  quantity: number;
  reason: string;
}

/** A Product's stock ledger entry (Prisma `StockMovement`), serialized for the API. */
export interface StockMovement {
  id: string;
  productId: string;
  productName: string;
  /** "IN" | "OUT" | "ADJUSTMENT" — kept as `string` since OUT rows (future POS sales) also list here. */
  type: string;
  quantity: number;
  reason: string;
  createdAt: string;
}

// ── POS Sales — Phase 2 Task 3 ──────────────────────────────────────────────
// Cash-only first pass (no returns/refunds/utang toko) — see
// docs/ksu-konsumen-backend.md "Explicitly out of scope for this plan".

export type PosPaymentMethod = "CASH" | "TRANSFER" | "MEMBER_CREDIT";

export interface CreateSaleLineRequest {
  productId: string;
  quantity: number;
}

export interface CreateSaleRequest {
  /** unitId must resolve to a KONSUMEN-type CooperativeUnit owned by the caller's tenant. */
  unitId: string;
  items: CreateSaleLineRequest[];
  paymentMethod: PosPaymentMethod;
  memberId?: string;
}

/** POSSale.totalPrice, Decimal(15,2) serialized as a string over the wire. */
export interface CreateSaleResponse {
  id: string;
  totalAmount: string;
}

/** A POSSale row (list view), serialized for the API. */
export interface PosSaleListItem {
  id: string;
  totalAmount: string;
  paymentMethod: string;
  memberId: string | null;
  soldAt: string;
  lineCount: number;
}

// ── PPOB (Payment Point Online Bank) — Phase 2 Task 4 ───────────────────────
// Deliberately a STUB: no real biller integration, purely a deterministic
// in-process simulation (see modules/konsumen/ppob.service.ts#simulateBill).
// No journal entry is posted for PPOB in this MVP — see that file's doc.

export type PpobBillType = "LISTRIK" | "PULSA" | "BPJS" | "AIR";

export interface CheckPPOBBillRequest {
  /** unitId must resolve to a CooperativeUnit owned by the caller's tenant. */
  unitId: string;
  billType: PpobBillType;
  customerNumber: string;
}

/** Simulated — amount/adminFee are Decimal-as-string per this codebase's money convention, even though nothing is real. */
export interface CheckPPOBBillResponse {
  amount: string;
  adminFee: string;
  customerName: string;
}

/**
 * Note: deliberately no `amount` field — the server re-derives it from the
 * same deterministic simulation `checkBill` used, so a client can never
 * assert an arbitrary paid amount. `adminFee` is accepted for API-contract
 * symmetry with the check step but is likewise re-derived server-side, never
 * trusted at face value.
 */
export interface PayPPOBBillRequest {
  unitId: string;
  billType: PpobBillType;
  customerNumber: string;
  adminFee: string;
}

export interface PayPPOBBillResponse {
  id: string;
  status: string;
}
