// KSU Konsumen (Toko/POS) — Phase 2 Task 2: Product CRUD + stock-movement
// tracking, scoped to a KONSUMEN-type CooperativeUnit. Field names here match
// the Phase 4 frontend plan (docs/ksu-konsumen-frontend.md) exactly, which is
// why they diverge from the raw Prisma column names (`price`/`cost`/
// `stockQty` become `sellPrice`/`costPrice`/`stockLevel` over the wire).

export type StockMovementType = "IN" | "ADJUSTMENT";

/** A Konsumen/Toko product (Prisma `Product`), serialized for the API. */
export interface Product {
  id: string;
  sku: string;
  name: string;
  category: string | null;
  uom: string;
  /** Product.price, Decimal(15,2) serialized as a string over the wire. */
  sellPrice: string;
  /** Product.cost, Decimal(15,2) serialized as a string over the wire. */
  costPrice: string;
  /** Product.stockQty (a plain int), exposed as a string per this contract. */
  stockLevel: string;
  isActive: boolean;
}

export interface CreateProductRequest {
  /** unitId must resolve to a KONSUMEN-type CooperativeUnit owned by the caller's tenant. */
  unitId: string;
  sku: string;
  name: string;
  category?: string;
  uom?: string;
  sellPrice: string | number;
  costPrice: string | number;
}

/**
 * `"OUT"` is deliberately not accepted here — it is system-generated by POS
 * sale posting (a later task), never manually entered by a caller of this
 * endpoint.
 */
export interface RecordStockMovementRequest {
  type: StockMovementType;
  quantity: number;
  reason: string;
}

/** A Product's stock ledger entry (Prisma `StockMovement`), serialized for the API. */
export interface StockMovement {
  id: string;
  productId: string;
  productName: string;
  /** "IN" | "OUT" | "ADJUSTMENT" — kept as `string` since OUT rows (future POS sales) also list here. */
  type: string;
  quantity: number;
  reason: string;
  createdAt: string;
}
