// KSU Konsumen (Toko/POS) — Phase 2 Task 2: Product CRUD + stock-movement
// tracking, scoped to a KONSUMEN-type CooperativeUnit. Field names here match
// the Phase 4 frontend plan (docs/ksu-konsumen-frontend.md) exactly, which is
// why they diverge from the raw Prisma column names (`price`/`cost`/
// `stockQty` become `sellPrice`/`costPrice`/`stockLevel` over the wire).

export type StockMovementType = "IN" | "ADJUSTMENT";

/** A Konsumen/Toko product (Prisma `Product`), serialized for the API. */
export interface Product {
  id: string;
  sku: string;
  name: string;
  category: string | null;
  uom: string;
  /** Product.price, Decimal(15,2) serialized as a string over the wire. */
  sellPrice: string;
  /** Product.cost, Decimal(15,2) serialized as a string over the wire. */
  costPrice: string;
  /** Product.stockQty (a plain int), exposed as a string per this contract. */
  stockLevel: string;
  isActive: boolean;
}

export interface CreateProductRequest {
  /** unitId must resolve to a KONSUMEN-type CooperativeUnit owned by the caller's tenant. */
  unitId: string;
  sku: string;
  name: string;
  category?: string;
  uom?: string;
  sellPrice: string | number;
  costPrice: string | number;
}

/**
 * `"OUT"` is deliberately not accepted here — it is system-generated by POS
 * sale posting (a later task), never manually entered by a caller of this
 * endpoint.
 */
export interface RecordStockMovementRequest {
  type: StockMovementType;
  quantity: number;
  reason: string;
}

/** A Product's stock ledger entry (Prisma `StockMovement`), serialized for the API. */
export interface StockMovement {
  id: string;
  productId: string;
  productName: string;
  /** "IN" | "OUT" | "ADJUSTMENT" — kept as `string` since OUT rows (future POS sales) also list here. */
  type: string;
  quantity: number;
  reason: string;
  createdAt: string;
}

// ── POS Sales — Phase 2 Task 3 ──────────────────────────────────────────────
// Cash/transfer were the first pass — see docs/ksu-konsumen-backend.md
// "Explicitly out of scope for this plan". MEMBER_CREDIT ("Kredit Anggota")
// went from an inert selectable value to a real payment method with
// eligibility checks and its own repayment flow — see the Member Credit
// section further below.

export type PosPaymentMethod = "CASH" | "TRANSFER" | "MEMBER_CREDIT";

export interface CreateSaleLineRequest {
  productId: string;
  quantity: number;
}

export interface CreateSaleRequest {
  /** unitId must resolve to a KONSUMEN-type CooperativeUnit owned by the caller's tenant. */
  unitId: string;
  items: CreateSaleLineRequest[];
  paymentMethod: PosPaymentMethod;
  memberId?: string;
}

/** POSSale.totalPrice, Decimal(15,2) serialized as a string over the wire. */
export interface CreateSaleResponse {
  id: string;
  totalAmount: string;
}

/** A POSSale row (list view), serialized for the API. */
export interface PosSaleListItem {
  id: string;
  totalAmount: string;
  paymentMethod: string;
  memberId: string | null;
  soldAt: string;
  lineCount: number;
}

// ── Member Credit ("Kredit Anggota") ────────────────────────────────────────
// A member-credit sale is a receivable, not cash-in-hand: `creditLimit` is
// auto-computed (50% of the member's total active savings balance across all
// types — no manually-set field), `outstandingBalance` is derived (sum of
// their MEMBER_CREDIT POSSale totals minus sum of their repayments), and
// `eligible` requires both an active saving AND a positive limit. Route
// permission is `konsumen:read`/`konsumen:update`, deliberately not
// `members:*` — a Kasir role typically has konsumen but not members
// permissions, and still needs to use this at the register.

export interface MemberCreditStatus {
  memberId: string;
  fullName: string;
  savingsBalance: string;
  creditLimit: string;
  outstandingBalance: string;
  availableCredit: string;
  hasActiveSaving: boolean;
  eligible: boolean;
}

/** A row in the tenant-wide "Piutang Anggota" list (GET /konsumen/pos/credit) — adds the display fields the list table needs (MemberDetailPage already has the full Member loaded, so the single-member status above doesn't carry them). */
export interface MemberCreditSummary extends MemberCreditStatus {
  memberNumber: string;
  accountNumber: string;
}

/** A lightweight member lookup result for the POS "Kredit Anggota" search — narrower than the full `Member` shape. */
export interface CreditMemberSearchResult {
  id: string;
  fullName: string;
  memberId: string;
  accountNumber: string;
}

export interface RecordCreditRepaymentRequest {
  memberId: string;
  amount: string | number;
  note?: string;
}

export interface RecordCreditRepaymentResponse {
  id: string;
  outstandingBalance: string;
}

// ── PPOB (Payment Point Online Bank) — Phase 2 Task 4 ───────────────────────
// Deliberately a STUB: no real biller integration, purely a deterministic
// in-process simulation (see modules/konsumen/ppob.service.ts#simulateBill).
// No journal entry is posted for PPOB in this MVP — see that file's doc.

export type PpobBillType = "LISTRIK" | "PULSA" | "BPJS" | "AIR";

export interface CheckPPOBBillRequest {
  /** unitId must resolve to a CooperativeUnit owned by the caller's tenant. */
  unitId: string;
  billType: PpobBillType;
  customerNumber: string;
}

/** Simulated — amount/adminFee are Decimal-as-string per this codebase's money convention, even though nothing is real. */
export interface CheckPPOBBillResponse {
  amount: string;
  adminFee: string;
  customerName: string;
}

/**
 * Note: deliberately no `amount` field — the server re-derives it from the
 * same deterministic simulation `checkBill` used, so a client can never
 * assert an arbitrary paid amount. `adminFee` is accepted for API-contract
 * symmetry with the check step but is likewise re-derived server-side, never
 * trusted at face value.
 */
export interface PayPPOBBillRequest {
  unitId: string;
  billType: PpobBillType;
  customerNumber: string;
  adminFee: string;
}

export interface PayPPOBBillResponse {
  id: string;
  status: string;
}
