import type {
  CheckPPOBBillRequest,
  CheckPPOBBillResponse,
  CreateProductRequest,
  CreateSaleRequest,
  CreateSaleResponse,
  CreditMemberSearchResult,
  MemberCreditStatus,
  PayPPOBBillRequest,
  PayPPOBBillResponse,
  Product,
  RecordCreditRepaymentRequest,
  RecordCreditRepaymentResponse,
  RecordStockMovementRequest,
  StockMovement
} from "@siskop/types";
import { apiFetch, apiPost } from "./client";

// Typed wrappers over apiFetch/apiPost for the Phase 2 Konsumen/Toko API
// (apps/backend/src/modules/konsumen/product.routes.ts, mounted at
// /api/konsumen/*). Uses the REAL DTOs from @siskop/types (CLAUDE.md rule 5)
// — no parallel Product/StockMovement interface declared here.

export function getProducts(unitId: string) {
  return apiFetch<Product[]>(`/konsumen/products?unitId=${encodeURIComponent(unitId)}`);
}

export function createProduct(unitId: string, input: Omit<CreateProductRequest, "unitId">) {
  return apiPost<Product>("/konsumen/products", { ...input, unitId });
}

export function getStockMovements(unitId: string) {
  return apiFetch<StockMovement[]>(`/konsumen/stock-movements?unitId=${encodeURIComponent(unitId)}`);
}

/**
 * `type` is deliberately typed via RecordStockMovementRequest ("IN" |
 * "ADJUSTMENT" only) — "OUT" is system-generated by POS sale posting and is
 * not a valid input here, matching product.schema.ts#recordStockMovementSchema.
 */
export function recordStockMovement(productId: string, input: RecordStockMovementRequest) {
  return apiPost<Product>(`/konsumen/products/${productId}/stock-movements`, input);
}

/**
 * POS checkout (sale.routes.ts's `POST /pos/sales`). `unitId` is part of the
 * body here (not a path param) per the real contract — callers pass it in
 * `input`, same as CreateSaleRequest requires.
 */
export function createPOSSale(input: CreateSaleRequest) {
  return apiPost<CreateSaleResponse>("/konsumen/pos/sales", input);
}

/**
 * PPOB (ppob.routes.ts, mounted alongside the rest of this module at
 * `/api/konsumen/*`) — a deterministic-simulation stub, no real biller. `check`
 * is a pure read (no side effect, safe to call repeatedly); `pay` re-derives
 * `amount` server-side from `(billType, customerNumber)` regardless of what a
 * client sends, so this wrapper doesn't even accept an `amount` param — the
 * request shape matches PayPPOBBillRequest exactly (unitId/billType/
 * customerNumber/adminFee only).
 */
export function checkPPOBBill(input: CheckPPOBBillRequest) {
  return apiPost<CheckPPOBBillResponse>("/konsumen/ppob/check", input);
}

export function payPPOBBill(input: PayPPOBBillRequest) {
  return apiPost<PayPPOBBillResponse>("/konsumen/ppob/pay", input);
}

/**
 * "Kredit Anggota" (member store credit) — credit.routes.ts, mounted
 * alongside pos/sales at `/api/konsumen/*`, gated on konsumen:read/update
 * (not members:*) so a Kasir who lacks members permissions can still use
 * these at the register.
 */
export function searchCreditMembers(search: string) {
  return apiFetch<CreditMemberSearchResult[]>(`/konsumen/pos/credit/members?search=${encodeURIComponent(search)}`);
}

export function getMemberCreditStatus(memberId: string) {
  return apiFetch<MemberCreditStatus>(`/konsumen/pos/credit/${memberId}`);
}

export function recordCreditRepayment(input: RecordCreditRepaymentRequest) {
  return apiPost<RecordCreditRepaymentResponse>("/konsumen/pos/credit/repayments", input);
}
