import type {
  CreateProductRequest,
  CreateSaleRequest,
  CreateSaleResponse,
  Product,
  RecordStockMovementRequest,
  StockMovement
} from "@siskop/types";
import { apiFetch, apiPost } from "./client";

// Typed wrappers over apiFetch/apiPost for the Phase 2 Konsumen/Toko API
// (apps/backend/src/modules/konsumen/product.routes.ts, mounted at
// /api/konsumen/*). Uses the REAL DTOs from @siskop/types (CLAUDE.md rule 5)
// — no parallel Product/StockMovement interface declared here.

export function getProducts(unitId: string) {
  return apiFetch<Product[]>(`/konsumen/products?unitId=${encodeURIComponent(unitId)}`);
}

export function createProduct(unitId: string, input: Omit<CreateProductRequest, "unitId">) {
  return apiPost<Product>("/konsumen/products", { ...input, unitId });
}

export function getStockMovements(unitId: string) {
  return apiFetch<StockMovement[]>(`/konsumen/stock-movements?unitId=${encodeURIComponent(unitId)}`);
}

/**
 * `type` is deliberately typed via RecordStockMovementRequest ("IN" |
 * "ADJUSTMENT" only) — "OUT" is system-generated by POS sale posting and is
 * not a valid input here, matching product.schema.ts#recordStockMovementSchema.
 */
export function recordStockMovement(productId: string, input: RecordStockMovementRequest) {
  return apiPost<Product>(`/konsumen/products/${productId}/stock-movements`, input);
}

/**
 * POS checkout (sale.routes.ts's `POST /pos/sales`). `unitId` is part of the
 * body here (not a path param) per the real contract — callers pass it in
 * `input`, same as CreateSaleRequest requires.
 */
export function createPOSSale(input: CreateSaleRequest) {
  return apiPost<CreateSaleResponse>("/konsumen/pos/sales", input);
}
