-- CreateEnum
CREATE TYPE "EquityClass" AS ENUM ('SIMPANAN_POKOK', 'SIMPANAN_WAJIB', 'MODAL_TETAP', 'CADANGAN_UMUM', 'CADANGAN_RISIKO', 'HIBAH', 'MODAL_PENYERTAAN', 'SHU', 'EKUITAS_LAIN');

-- AlterTable
ALTER TABLE "Account" ADD COLUMN "equityClass" "EquityClass";
